import image1 from "../../Pages/Services/services-images/image1.png";
import image2 from "../../Pages/Services/services-images/image2.png";
import image3 from "../../Pages/Services/services-images/image3.png";
import image4 from "../../Pages/Services/services-images/image4.png";
import image5 from "../../Pages/Services/services-images/image5.png";
import image6 from "../../Pages/Services/services-images/image6.png";
import image7 from "../../Pages/Services/services-images/image7.png";
import image8 from "../../Pages/Services/services-images/image8.png";

let servicesData=[
    { id:1,image:image1,imageName:"1. Big Data",content:`Big data is a broad term for data sets so large or complex that traditional data processing applications are inadequate. Challenges include analysis, capture, data curation, search, sharing, storage, transfer, visualization, querying and information privacy. The term often refers simply to the use of predictive analytics or certain other advanced methods to extract value from data, and seldom to a particular size of data set. Accuracy in big data may lead to more confident decision making, and better decisions can result in greater operational efficiency, cost reduction and reduced risk.Analysis of data sets can find new correlations to “spot business trends, prevent diseases, combat crime and so on.`},
    
    { id:2,image:image2,imageName:"2. Cloud Computing",content:`Cloud computing is a general term for the delivery of hosted services over the Internet. Cloud computing enables companies to consume compute resources as a utility - just like electricity - rather than having to build and maintain computing infrastructures in-house. Cloud computing promises several attractive benefits for businesses and end users. Three of the main benefits of cloud computing include: Self-service provisioning: End users can spin up computing resources for almost any type of workload on-demand. Elasticity: Companies can scale up as computing needs increase and then scale down again as demands decrease. Pay per use: Computing resources are measured at a granular level, allowing users to pay only for the resources and workloads they use. Cloud computing services can be private, public or hybrid.`},
    
    { id:3,image:image3,imageName:"3. Enterprise Applications in Java,.net & PHP ",content:`First and foremost, Java and PHP are languages while .NET is a framework. User Friendliness is generally for an application - it is called UX. Frameworks are generally rated as developer friendly and not as user friendly. So, here is my comparison between the following technology frameworks: Java + J2EE (Spring, Hibernate) - highly developer friendly. Mostly open source and easy to find a great deal of experienced developers on this technology stack. Is truly vendor independent. Scalability is very high and perfomance tuning can be very granular. PHP + (Laravel/CI/Cake PHP | WordPress/Drupal/Magento) - Mostly deployed as a LAMP Stack and thus is most cost effective. Security depends on the developer as the technology stack needs to be configured to suit your needs - yet is considered 
    secure based on the community support. `},
    
    { id:4,image:image4,imageName:"4. Mobile App Development",content:`Mobile application development is a term used to denote the act or process by which application software is developed for handheld devices, such as personal digital assistants, enterprise digital assistants or mobile phones. These applications can be pre-installed on phones during manufacturing platforms, or delivered as web applications using server-side or client-side processing (e.g. JavaScript) to provide an “application-like” experience within a Web browser. Application software developers also have to consider a lengthy array of screen sizes, hardware specifications and configurations because of intense competition in mobile software and changes within each of the platforms. Mobile app development has been steadily growing, both in terms of revenues and jobs created.`},
    
    { id:5,image:image5,imageName:"5. NFIC & RFID services",content:`NFC (Near Field Communication) is a technology used in contactless IC cards. It allows mutual communications, authentication, payment, and various types of settings to be performed by simply hold an electronic device over the reader. This technology is based on the NFC standard of the 13.56 MHz band developed by NXP Semiconductors and Sony. FeliCa, the smart card used for payment of transportation services and as an e-money card, and MIFARE, the most commonly used chip in the world, are both compatible with the NFC standard. Not only is information read and written, but data can also be transmitted. Approved by the International Organization for Standardization (ISO), NFC is the next-generation standard of RFID technology, expected to be applied to various electronic devices in the future.`},
    
    { id:6,image:image6,imageName:"6. Oracle Applications",content:`Oracle Applications means software that helps you runs your enterprise businesses such as Accounting, Humans Resource, or Financials. But the Oracle Applications Server is the technology that, mostly installs on the server, integrates others software to work together. It can be called Middleware. Oracle’s E-Business Suite (also known as Applications/Apps or EB-Suite/EBS) consists of a collection of enterprise resource planning (ERP), customer relationship management (CRM), and supply-chain management (SCM) computer applications either developed or acquired by Oracle.`},
    
    { id:7,image:image7,imageName:"7. SAP",content:`SAP is the best-in-class ERP system. That’s why you chose it. That’s why your organization made a significant investment of time and resources to implement it as your system of record. Despite this, many organizations look to implement solutions that use other workflow engines when they want to improve their business processes. Dolphin takes an SAP-centric approach to business process optimization. Our solutions incorporate pre-built workflows that are based on line of business (i.e., Accounts Payable, Accounts Receivable, Order Management and Human Resources) and SAP system best practices. By leveraging the power of the SAP Business Workflow engine, we can provide our customers with solutions that are fast, flexible and cost-effective.`},
    
    { id:8,image:image8,imageName:"8. Training & Placement",content:`Technology has become a part of our daily life and who knows what the future will bring? One thing is for sure that it will bring plenty of job opportunities for those who are highly skilled and trained. At NFC Solutions we provide Role based training on an individual basis. We understand your need and design a program around you. We provide a Career Counseling program with individual attention which helps you decide a career in IT you can choose. NFC Solutions unique Competency Development Program provides a concrete, structured framework for systematic measurement and planning of talent development. We focus on providing world class service to organizations that remain competitive. We have been successful in providing world class service to clients. We have immense experience & expertise 
    in the field of corporate training. `},
     
]
export default servicesData;